# Generated by Django 5.2.5 on 2026-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='use_existing_images',
            field=models.BooleanField(default=False, help_text='If True, skip image research and use existing Pinecone images only (faster, requires prior indexing)'),
        ),
    ]
