# Generated by Django 5.2.5 on 2026-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('computer_science', 'Computer Science'), ('other', 'Other')], default='mathematics', max_length=32),
        ),
    ]
