# Generated by Django 5.2.5 on 2026-02-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_difficulty_lesson_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='lessons.lesson'),
        ),
    ]
