# Generated by GitHub Copilot on 2026-02-19

import base64

from django.core.files.base import ContentFile
from django.db import migrations


_PNG_1X1_BASE64 = (
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/xcAAwMB'
    '/6X0kQAAAABJRU5ErkJggg=='
)


def seed_pythagorean_lesson(apps, schema_editor):
    Lesson = apps.get_model('lessons', 'Lesson')

    title = 'Pythagorean Theorem'
    if Lesson.objects.filter(title__iexact=title).exists():
        return

    lesson = Lesson(
        title=title,
        subject='mathematics',
        difficulty='beginner',
        plan=(
            'Learn the Pythagorean theorem (a² + b² = c²) and practice applying '
            'it to solve right-triangle problems.'
        ),
    )

    png_bytes = base64.b64decode(_PNG_1X1_BASE64)
    lesson.thumbnail.save('pythagorean.png', ContentFile(png_bytes), save=False)
    lesson.save()


def unseed_pythagorean_lesson(apps, schema_editor):
    Lesson = apps.get_model('lessons', 'Lesson')
    Lesson.objects.filter(title__iexact='Pythagorean Theorem').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessonprogress'),
    ]

    operations = [
        migrations.RunPython(seed_pythagorean_lesson, unseed_pythagorean_lesson),
    ]
