# Generated by GitHub Copilot on 2026-02-19

from django.db import migrations


def fix_plan_ascii(apps, schema_editor):
    Lesson = apps.get_model('lessons', 'Lesson')
    Lesson.objects.filter(title__iexact='Pythagorean Theorem').update(
        plan=(
            'Learn the Pythagorean theorem (a^2 + b^2 = c^2) and practice applying '
            'it to solve right-triangle problems.'
        )
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_seed_pythagorean_lesson'),
    ]

    operations = [
        migrations.RunPython(fix_plan_ascii, noop_reverse),
    ]
