# Generated by Django 5.2.5 on 2026-02-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_add_use_elevenlabs_tts'),
        ('lessons', '0007_fix_pythagorean_plan_ascii'),
    ]

    operations = [
    ]
