# Generated by Django 5.2.5 on 2026-02-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_merge_20260225_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='resume_playback_time',
            field=models.FloatField(default=0.0, help_text='Playback position in seconds (global timeline time) for continue-lesson'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='resume_segment_index',
            field=models.PositiveIntegerField(default=0, help_text='Last-played segment index for continue-lesson feature'),
        ),
    ]
