# Generated by Django 5.2.5 on 2025-10-29 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.JSONField()),
                ('total_duration', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='lessons.lessonsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('speech_text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='timeline_audio/')),
                ('actual_audio_duration', models.FloatField(blank=True, null=True)),
                ('drawing_actions', models.JSONField()),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_records', to='timeline_generator.timeline')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('timeline', 'sequence_number')},
            },
        ),
    ]
