# Generated by Django 5.2.5 on 2026-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradeproposal',
            name='proposed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
