# Generated by Django 5.2.5 on 2026-02-18 00:00

from django.db import migrations, models


def set_unit_price_from_item(apps, schema_editor):
    MarketListing = apps.get_model('market', 'MarketListing')
    for listing in MarketListing.objects.select_related('item').all():
        if listing.unit_price is None and listing.item is not None:
            listing.unit_price = listing.item.price
            listing.save(update_fields=['unit_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_marketlisting_quantity_owneditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(set_unit_price_from_item, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='marketlisting',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
