# Generated by Django 5.2.5 on 2026-02-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_marketlisting_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketlisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='available', max_length=50),
        ),
    ]
