# Generated by Django 5.2.5 on 2026-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePicture',
            new_name='Avatar',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='current_pfp',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='owned_pictures',
            new_name='owned_avatars',
        ),
        migrations.AddField(
            model_name='customuser',
            name='inventory',
            field=models.ManyToManyField(blank=True, to='market.marketitem'),
        ),
    ]
