# Generated by Django 5.2.5 on 2025-08-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='profile_pictires/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pfp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pfp', to='users.profilepictures'),
        ),
    ]
