# Generated by Django 5.2.5 on 2026-02-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_counteroffer'),
        ('users', '0002_rename_profilepicture_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='owners', to='market.marketitem'),
        ),
    ]
