# Generated by Django 5.2.5 on 2025-08-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pictures/')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pfp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_pfp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='users.profilepicture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='owned_pictures',
            field=models.ManyToManyField(blank=True, to='users.profilepicture'),
        ),
        migrations.DeleteModel(
            name='ProfilePictures',
        ),
    ]
